### PR TITLE
moved terms to command line option

### PR DESCRIPTION
**Pull request by asayeed**
Now you can change the terms on the command line, what fun.

### CODE REVIEW

**Comment by BayesForDays** [comment]
I like it, but perhaps we could set defaults? This package is partly a convenience function, too. Even something like `en` and `covid-10` would work I think.

**Comment by asayeed** [comment]
The language option left blank just downloads all languages I think.  I've never used click before, let me check on how to set defaults.

**Comment by asayeed** [comment]
I also added an extractor script called reagent.py. It just formats the downloaded json as a table given extraction keys.

**Comment by BayesForDays** [comment]
I like the reagent script idea! I actually just realized it's much better as a standalone, it's a pretty interesting CLI too.

**Pull request merged**
